[package]
name = "graphql-rust"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.3.1"
actix-web-lab = "0.19.1"
env_logger = "0.10.0"
juniper = "0.15"
log = "0.4.17"
serde = "1.0.159"
serde_json = "1.0.95"
